export default {
    HeroHeading : 'AI Logo Maker',
    HeroSubheading : 'Perfect Logos for Apps, Businesses, and Websites',
    HeroDesc:'Craft unique and professional logos effortlessly with our AI powered tool. Perfect for apps, businesses,websites, and more!',
    InputTitlePlaceholder : 'Enter your Logo Name',
     LogoTitle: "Logo Title",
    LogoTitleDesc: "Add Your Brand, App or Website Name Here for Your Logo",
    InputTitlePlaceholder: "Enter Your Logo Name Here",
    LogoDescTitle: "Describe Your Logo Vision",
    LogoDescDesc: "Share your ideas, themes, or inspirations to create a logo that resonates with your audience",
    InputDescPlaceholder: "Enter Your Logo Description Here",
    LogoColorPaletteTitle: "Logo Color Palette",
    LogoColorPaletteDesc: "Select Your Preferred Color Palette for Your Logo",
    LogoDesignTitle: "Choose Your Logo Design",
    LogoDesignDesc: "Select Your Preferred Logo Design for Your Logo",
    LogoPricingModelTitle:"Select your AI Model Plan",
    LogoPricingModelDescription:"Generate Unlimited Fast Logo with your fav model",
    LogoTitleIdea:"Logo Title Idea",
    LogoIdeaDesc: "Select Your Preferred Logo Ideas for Your Logo"
}