import { Host_Grotesk } from "next/font/google";
import "./globals.css";
import Provider from "./provider";
import { ClerkProvider } from "@clerk/nextjs";

const host_grotesk = Host_Grotesk({
  subsets : ['latin']
})

export const metadata = {
  title: "Wishcraft -Logo maker",
  description: "Generated by create next app",
   icons: {
    icon: '/reshot-icon-pencil-U3A6CNXBDH.svg', 
  },
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>

       <html lang="en">
      <body
        className={host_grotesk.className}
      >
        <Provider>
          {children}
        </Provider>
        
      </body>
    </html>
    </ClerkProvider>
   
  );
}
